parameters:
  serviceConnection: ''
  subscription: ''
  resourceGroup: ''
  location: 'West Europe'
  appServiceName: ''
  appServicePlanName: ''
  sku: 'F1'
  appInsightsLocation: 'WestEurope'

steps:
- script: dir $(Build.ArtifactStagingDirectory)
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'ARM Template deployment: Resource Group scope'
  inputs:
    azureResourceManagerConnection: '${{ parameters.serviceConnection }}'
    subscriptionId: '${{ parameters.subscription }}'
    resourceGroupName: '${{ parameters.resourceGroup }}'
    location: '${{ parameters.location }}'
    csmFile: 'ArmTemplates/windows-webapp-template.json'
    overrideParameters: '-webAppName ${{ parameters.appServiceName }} -hostingPlanName ${{ parameters.appServicePlanName }} -appInsightsLocation ${{ parameters.appInsightsLocation }} -sku ${{ parameters.sku }}'
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    WebAppName: '$(AppServiceName)'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app/SampleWebApplication.zip'
