# Variables to set in Azure Pipelines:
# SolutionPath: path to .sln file
# Variables to set in variable groups TEST and PROD:
# Subscription: Azure subscription ID
# ResourceGroup: azure resource group
# AppServiceName: azure app service name
# AppServicePlanName: azure app service plan name

trigger: 
  - master

pool:
  name: Azure Pipelines
  vmImage: windows-2019

variables:
  ServiceConnection: 'workshop-azure'

stages:
- stage: Build
  jobs:
  - job: build_app
    steps:
    - template: templates/build.yml
      parameters:
        solutionPath: $(SolutionPath)

- stage: Deploy_TEST
  dependsOn: ['Build']
  variables:
  - group: 'TEST'
  jobs:
  - template: templates/deploy.yml
    parameters:
      environment: TEST
      serviceConnection: $(ServiceConnection)
      subscription: $(Subscription)
      resourceGroup: $(ResourceGroup)
      appServiceName: $(AppServiceName)
      appServicePlanName: $(AppServicePlanName)

- stage: Verify_TEST
  dependsOn: ['Deploy_TEST']
  variables:
    - group: 'TEST'
    - name: ApplicationUrl
      value: 'https://$(AppServiceName).azurewebsites.net'
  jobs:
  - job: verify_app
    steps:
    - template: templates/verify.yml
      parameters:
        webAppUrl: '$(ApplicationUrl)'

- stage: Deploy_PROD
  dependsOn: ['Verify_TEST']
  variables:
  - group: 'PROD'
  jobs:
  - template: templates/deploy.yml
    parameters:
      environment: PROD
      serviceConnection: $(ServiceConnection)
      subscription: $(Subscription)
      resourceGroup: $(ResourceGroup)
      appServiceName: $(AppServiceName)
      appServicePlanName: $(AppServicePlanName)
  
    
