# Variables to set in Azure Pipelines:
# SolutionPath: path to .sln file

trigger: 
  - master

pool:
  name: Azure Pipelines
  vmImage: windows-2019

steps:
- template: templates/build.yml
  parameters:
    solutionPath: $(SolutionPath)
    
