# Variables to set in Azure Pipelines:
# SolutionPath: path to .sln file
# Subscription: Azure subscription ID

trigger: 
  - master

pool:
  name: Azure Pipelines
  vmImage: windows-2019

variables:
  ServiceConnection: 'workshop-azure'

stages:

steps:
- template: templates/build.yml
  parameters:
    solutionPath: $(SolutionPath)

- template: templates/deploy.yml
  parameters:
    serviceConnection: $(ServiceConnection)
    subscription: $(Subscription)
    resourceGroup: 'workshop-test-pl'
    appServiceName: 'workshop-test-app-pl'
    appServicePlanName: 'workshop-test-plan-pl'

- template: templates/deploy.yml
  parameters:
    serviceConnection: $(ServiceConnection)
    subscription: $(Subscription)
    resourceGroup: 'workshop-prod-pl'
    appServiceName: 'workshop-prod-app-pl'
    appServicePlanName: 'workshop-prod-plan-pl'
  
    
