trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  Solution: 'Library/MyLibrary.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.6.0'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(Solution)'

- task: VSBuild@1
  inputs:
    solution: '$(Solution)'
    vsVersion: '16.0'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'Library/MyLibrary/MyLibrary.csproj'
    versioningScheme: 'off'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'bc94f718-e0ec-40f5-be83-d17f303d4a91/f351905f-9036-4ad6-842d-e64433140c22' # use your feed here